<a href="https://colab.research.google.com/github/IshtiSikder/Optimal-allocation-of-rescue-teams-for-hostage-situations/blob/updates/R_for_MDP_(NEW).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cost equations are improved (15th May, 23)

In [124]:
# CTMC MDP model for rescue operational system!!!

# Check function to determine new policy is same with current or not 
checkPolicy = function(policySet, policySetnew) {
  n = 0
  for (i in policySet == policySetnew) {
    if (i == 'FALSE') {
      n = 1
    } 
  } 
  if (n == 0) {
    return("TRUE")
  } else {
    return("FALSE")
  }
} 


# Define MDP function (for basic policy)
MDP = function(lam, mu, eps, numRescue, numTerror, costT, RC, mult) {
  r = numRescue
  t = numTerror
  
  #calculating costR

  costR = mult*costT*(mu+eps)


  #########################################################
  #EDITS: 22ND FEB,2023
  #NEW SERVICE RATES STRUCTURE, ADD ORIGINAL ONE AS WELL
  aijMatrix = array(0, dim = c(t+1,t+1,r+1))
  for (k in 1:(r+1)) {
    for (i in 1:t) {
      aijMatrix[i,i+1,k] <- lam
      if (i > 1) {
        #if (k==4){
          #if(i==4){
            #cat('min(k-1,i-1)',min(k-1,i-1))}}
        aijMatrix[i,i-1,k] <- sum(min(k-1,i-1)*mu+(i-1)*eps)        
      }
    }
    aijMatrix[t+1,t,k] <- (min(k-1,t)*mu+t*eps)
    aijMatrix[1,2,k] <- lam
}

  for (k in 1:(r+1)) {
    for (i in 1:(t+1)) {
      
      aijMatrix[i,i,k] <- -sum(aijMatrix[i,,k])      
    }
  }
  #########################################################
  
  
  # Design the MDP algorithm
  # Value determination
  policy = array(0, dim = c(1,t+1)) 
  policyOld = array(0, dim = c(1,t+1))
  policyNew = array(2, dim=c(1,t+1)) # initially set all decision is 1 in first policy
  policyTrack = array(2, dim=c(1,t+1))
  iteration = 0
  gainMatrix = c()
  
  while (checkPolicy(policyOld, policyNew) == 'FALSE') {
    policyOld = policyNew
    policy = policyNew
    # Design the transition matrix regarding policy
    A = array(0, dim = c(t+1,t+1))
    for (i in 1:length(policy)) {
      A[i,] = aijMatrix[i,,(policy[i])]  
    }

    # Design the cost matrix regarding policy

    q = array(0,dim=c(t+1,1))
    for (i in 1:length(policy)) {

      if (RC == 'L'){
      cost = (policy[i]-1)*costR + (i-1)*eps*costT
      }

      if (RC == 'SR'){
      cost = sqrt(policy[i]-1)*costR + (i-1)*eps*costT
      }

      if (RC == 'Q'){
      cost = ((policy[i]-1)^2)*costR + (i-1)*eps*costT
      }

      q[i,1] = cost
    }


    newA = cbind(array(1, dim=c(t+1,1)), -A[,1:t])
    solution = solve(newA) %*% q
    gain = solution[1] # First row of solution is gain value
    gainMatrix = append(gainMatrix, gain)
    
    # Policy improvement
    newsolution = array(0, dim=c(t+1,1))
    for (i in 1:t) {
      newsolution[i] = solution[i+1]
    }
    newsolution[t+1] = 0 # Set last v value as 0 to calcultate the test quantity in policy improvement
    improveMatrix = array(0, dim=c(t+1,r+1))
    cost = array(0,dim=c(t+1,r+1))

    for (i in 1:(t+1)) {
      for (j in 1:(r+1)) {
        # Cost when we have j rescue operation and i terrorists

        if (RC == 'L'){
      cost[i,j] = (j-1)*costR + (i-1)*eps*costT
      }

      if (RC == 'SR'){
      cost[i,j] = sqrt(j-1)*costR + (i-1)*eps*costT
      }

      if (RC == 'Q'){
      cost[i,j] = ((j-1)^2)*costR + (i-1)*eps*costT
      }

        improveMatrix[i,j] = cost[i,j] + aijMatrix[i,,j] %*% newsolution

      }
    }  
    
    # pick the minimum value among the decision
    policyNew = array(1, dim = c(1,t+1))
    for (i in 1:length(policyNew)) {
      policyNew[i] = which.min(improveMatrix[i,])
    }
    iteration = iteration + 1
    policyTrack = rbind(policyTrack, policyNew)
    policyNew
  }
  for (i in 1:length(policyNew)) {
    policyNew[i] = policyNew[i] - 1
  }
  for (i in 1:nrow(policyTrack)) {
    for (j in 1:ncol(policyTrack)) {
      policyTrack[i,j] = policyTrack[i,j] - 1      
    }

  }

  
   #return(list(policyNew,improveMatrix,cost,aijMatrix,newsolution))

   return (policyNew)
 
 }

In [128]:
mult_test = function(cost_terror,rc,low_lim,up_lim,incr) {

prev_result = array(100,dim=c(1,11))

for (val in seq(low_lim,up_lim, by = incr)){

        current_result = MDP(lam = 0.2763, mu = 0.2829, eps = 0.1718, numRescue=10, numTerror=10, costT=cost_terror, RC=rc, mult=val)
         
        if (!(identical(current_result,prev_result))) {

          cat('\n\n','mult:',val,',','RC:',rc,',','\n\n')
          cat('optimal policy:\n')
          print(current_result)
          

          prev_result = current_result

        }

    }

}

In [129]:
mult_test(1,'L',0,100,0.01)



 mult: 0 , RC: L , 

optimal policy:
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    2    3    4    5    6    7    8     9    10


 mult: 0.54 , RC: L , 

optimal policy:
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    2    3    4    5    6    7    8     9     0


 mult: 0.61 , RC: L , 

optimal policy:
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    2    3    4    5    6    7    8     0     0


 mult: 0.62 , RC: L , 

optimal policy:
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    2    3    4    5    6    7    0     0     0


 mult: 0.63 , RC: L , 

optimal policy:
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    0    0    0    0    0    0    0    0     0     0


Linear structure, different factor values

In [16]:
mult_test(1,'L',0,100,0.01)



 mult: 0 , RC: L , 

optimal policy:
[[1]]
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    2    3    4    5    6    7    8     9    10



 mult: 0.54 , RC: L , 

optimal policy:
[[1]]
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    2    3    4    5    6    7    8     9     0



 mult: 0.61 , RC: L , 

optimal policy:
[[1]]
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    2    3    4    5    6    7    8     0     0



 mult: 0.62 , RC: L , 

optimal policy:
[[1]]
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    2    3    4    5    6    7    0     0     0



 mult: 0.63 , RC: L , 

optimal policy:
[[1]]
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    0    0    0    0    0    0    0    0     0     0



Linear cost structure, factor value = 1

In [ ]:
MDP(lam = 0.2763, mu = 0.2829, eps = 0.1718, numRescue=10, numTerror=10,costT=1, RC='L',mult=1)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,] 0    0    0    0    0    0    0    0    0    0     0

Square root cost structure, different factor values

In [ ]:
mult_test(1,'SR',0,100,0.01)

mult: 0 , RC: SR , 

0 1 2 3 4 5 6 7 8 9 10 

mult: 0.5 , RC: SR , 

0 0 2 3 4 5 6 7 8 9 10 

mult: 0.78 , RC: SR , 

0 0 0 3 4 5 6 7 8 9 10 

mult: 1.01 , RC: SR , 

0 0 0 0 4 5 6 7 8 9 10 

mult: 1.2 , RC: SR , 

0 0 0 0 0 5 6 7 8 9 10 

mult: 1.36 , RC: SR , 

0 0 0 0 0 0 6 7 8 9 10 

mult: 1.5 , RC: SR , 

0 0 0 0 0 0 0 7 8 9 10 

mult: 1.63 , RC: SR , 

0 0 0 0 0 0 0 0 8 9 10 

mult: 1.66 , RC: SR , 

0 0 0 0 0 0 0 0 8 9 0 

mult: 1.75 , RC: SR , 

0 0 0 0 0 0 0 0 0 9 0 

mult: 1.82 , RC: SR , 

0 0 0 0 0 0 0 0 0 0 0 



Square root cost structure, factor value = 1

In [ ]:
MDP(lam = 0.2763, mu = 0.2829, eps = 0.1718, numRescue=10, numTerror=10,costT=1, RC='SR',mult=1)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,] 0    0    0    3    4    5    6    7    8    9     10

Quadratic cost structure, different factor values

In [ ]:
mult_test(1,'Q',0,100,0.01)

mult: 0 , RC: Q , 

0 1 2 3 4 5 6 7 8 9 10 

mult: 0.02 , RC: Q , 

0 1 2 3 4 5 6 7 8 9 9 

mult: 0.03 , RC: Q , 

0 1 2 3 4 5 6 6 6 7 6 

mult: 0.04 , RC: Q , 

0 1 2 3 4 5 5 5 5 5 5 

mult: 0.05 , RC: Q , 

0 1 2 3 4 4 4 4 5 5 4 

mult: 0.06 , RC: Q , 

0 1 2 3 3 4 4 4 4 4 4 

mult: 0.07 , RC: Q , 

0 1 2 3 3 3 3 3 3 4 3 

mult: 0.08 , RC: Q , 

0 1 2 3 3 3 3 3 3 3 3 

mult: 0.09 , RC: Q , 

0 1 2 2 3 3 3 3 3 3 3 

mult: 0.1 , RC: Q , 

0 1 2 2 2 2 3 3 3 3 2 

mult: 0.11 , RC: Q , 

0 1 2 2 2 2 2 2 2 2 2 

mult: 0.16 , RC: Q , 

0 1 1 2 2 2 2 2 2 2 2 

mult: 0.17 , RC: Q , 

0 1 1 1 2 2 2 2 2 2 1 

mult: 0.18 , RC: Q , 

0 1 1 1 1 2 2 2 2 2 1 

mult: 0.19 , RC: Q , 

0 1 1 1 1 1 1 2 2 2 1 

mult: 0.2 , RC: Q , 

0 1 1 1 1 1 1 1 1 1 1 

mult: 0.53 , RC: Q , 

0 1 1 1 1 1 1 1 1 1 0 

mult: 0.61 , RC: Q , 

0 1 1 1 1 1 1 1 1 0 0 

mult: 0.62 , RC: Q , 

0 1 1 1 1 1 1 1 0 0 0 

mult: 0.63 , RC: Q , 

0 0 0 0 0 0 0 0 0 0 0 



Quadratic cost structure, factor value = 1

In [ ]:
MDP(lam = 0.2763, mu = 0.2829, eps = 0.1718, numRescue=10, numTerror=10,costT=1, RC='Q',mult=1)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,] 0    0    0    0    0    0    0    0    0    0     0